import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { UIProvider } from "@/context/UIContext";
import "@/components/layout/LayoutWrapper"; // ensure component is included in bundle
import LayoutWrapper from "@/components/layout/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Use LayoutWrapper to provide shared header and sidebar across pages */}
        <div className="min-h-screen">
          {/* LayoutWrapper is client component and is safe to import here via dynamic or as client component tree */}
          <div id="app-layout">
            {/* We render LayoutWrapper directly so pages get consistent header/sidebar */}
            {/* Note: LayoutWrapper uses Header and Sidebar which are client components */}
            {/* eslint-disable-next-line @next/next/no-sync-scripts */}
            <AuthProvider>
              <UIProvider>
                <LayoutWrapper>
                  {children}
                </LayoutWrapper>
              </UIProvider>
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
